// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWTT4YG9O1-mzjAVbz7yiHxVXu02xLDv4',
    appId: '1:937029182282:web:bafa94d53c6185589fd7b3',
    messagingSenderId: '937029182282',
    projectId: 'parqpilot-2c029',
    authDomain: 'parqpilot-2c029.firebaseapp.com',
    storageBucket: 'parqpilot-2c029.firebasestorage.app',
    measurementId: 'G-ZR0D6074Z1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4kwGCyoVorFYgMPW_22cZ7koZbn4oq2k',
    appId: '1:937029182282:android:6736d66e6e0f341e9fd7b3',
    messagingSenderId: '937029182282',
    projectId: 'parqpilot-2c029',
    storageBucket: 'parqpilot-2c029.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLyMPSLOTw8KxbdbhjjHaYa2hhxAQUArA',
    appId: '1:937029182282:ios:82035eb9fc5840c89fd7b3',
    messagingSenderId: '937029182282',
    projectId: 'parqpilot-2c029',
    storageBucket: 'parqpilot-2c029.firebasestorage.app',
    iosBundleId: 'com.example.parqpilot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLyMPSLOTw8KxbdbhjjHaYa2hhxAQUArA',
    appId: '1:937029182282:ios:82035eb9fc5840c89fd7b3',
    messagingSenderId: '937029182282',
    projectId: 'parqpilot-2c029',
    storageBucket: 'parqpilot-2c029.firebasestorage.app',
    iosBundleId: 'com.example.parqpilot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWTT4YG9O1-mzjAVbz7yiHxVXu02xLDv4',
    appId: '1:937029182282:web:ef6d427596965ebf9fd7b3',
    messagingSenderId: '937029182282',
    projectId: 'parqpilot-2c029',
    authDomain: 'parqpilot-2c029.firebaseapp.com',
    storageBucket: 'parqpilot-2c029.firebasestorage.app',
    measurementId: 'G-ZD7G2ZJP0J',
  );
}
